### ISSUE TITLE
popmap pops not assigned correctly in the assess_missing_data function

### ISSUE THREAD

**Issue by DevonDeRaad** [DevonDeRaad/SNPfiltR#2]
I identified a bug where the designated popmap populations will at times not be assigned correctly, meaning that when you run assess_missing_data_pca(), your populations will not be colored according to the popmap you specify. This is happening because the code 'order(popmap$id == colnames(vcfR@gt)[-1])' is not working to correctly match the popmap IDs to the individual order in the vcfR object. Replacing this code with 'order(match(popmap$id,colnames(v@gt)[-1]))' seems to work, e.g., in line 413 of the assess_missing_data_pca() function. This bug will require modifications to both the assess_missing_data_pca() and assess_missing_data_tsne() functions, and a corresponding new version release.

**Comment by loukiaspi** [comment]
Hi, I have been using your package and came here to open another issue and bumped into this. Does the fact that this is still open mean that the bug is still present in the current version? Asking so that I know to what extent I should take the plots of the two assess_missing_data functions into account

**Comment by DevonDeRaad** [comment]
Hi, you are correct that this is still an issue that I have not had time to fix. If your input popmap order does not match the order of your samples in the input vcf, then the color-coding of the samples in the output 2D scatterplots of PC1 and PC2 will be incorrect. The plots color-coded by proportion of missing data in each of these functions will still be accurate. I will update this thread when this bug has been fixed.

**Comment by DevonDeRaad** [comment]
Commit ba9395e should now have solved this issue. Datasets run using the development version of the package should no longer have to have the input popmap in identical order to the samples in the vcf.

**Comment by DevonDeRaad** [comment]
This bug fix is now incorporated into the development and release (CRAN) versions of the package - as of v1.0.1
