### ISSUE TITLE
filter_allele_balance() not working when the allele count data are in the CATG form instead of the AD form

### ISSUE THREAD

**Issue by loukiaspi** [DevonDeRaad/SNPfiltR#3]
Hi, I have been trying to use the **filter_allele_balance()** function to filter my data but so far it has proven unsuccessful. The error message that I was getting was **"allele depth is not specified in input vcf, therefore allele balance cannot be calculated"**. However, I knew that my data does include allele depth information so this didn't make sense. So I looked through the source code of the function and I realized that I am getting this warning because the function is expecting to find the allele depth in the AD form whereas mine is in the CATG form. I tried to solve this by modifying your original function but my coding abilities are minimal so I was unsuccessful. Is it possible to get allele depth from the CATG format some other way? Could it be something that you could implement in a subsequent version?

Thanks in advance

P.S: I am attaching a tiny portion of my data so that you can see the format by yourself, rather than me describing it
[vcfR_test .vcf.txt](https://github.com/DevonDeRaad/SNPfiltR/files/10467096/vcfR_test.vcf.txt)

**Comment by DevonDeRaad** [comment]
Hi, thanks for this suggestion. I have pushed a new commit that updates the code for the function filter_allele_balance() to perform this filter using allele depths specified in 'CATG' format. If you want to try it out, it should be as easy as updating your installed version of SNPfiltR to the current development version using the code 'devtools::install_github("DevonDeRaad/SNPfiltR")', and then re-running the function on your vcf using the new version of the package.

For what it's worth, I had a hard time figuring out how to use the 'CATG' format efficiently. I basically added a module within the function that recognizes the format and converts 'CATG' format into 'AD' format, but it is pretty inefficient. Essentially, each individual cell in the matrix of your vcf, which is # of samples x # of SNPs wide, must be indexed to isolate the reference and alternate allele depths from the other two non-relevant allele depths to do this conversion. Hopefully if you don't mind being a bit patient, this implementation will work for you.

Best wishes,
Devon

**Comment by loukiaspi** [comment]
Hi Devon, thanks for the implementation. I tried to update my version to the current development version and got this:

> devtools::install_github("DevonDeRaad/SNPfiltR")
Downloading GitHub repo DevonDeRaad/SNPfiltR@HEAD
── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/w3/n_9mjknj6vzf79xvgjwjln9m0000gn/T/RtmpXOseFi/remotes61b3fb2aaa0/DevonDeRaad-SNPfiltR-e9c147e/DESCRIPTION’ ...
─  preparing ‘SNPfiltR’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘SNPfiltR_1.0.0.tar.gz’
   
* installing *source* package ‘SNPfiltR’ ...
** using staged installation
** R
Error in parse(outFile) : 
  /private/var/folders/w3/n_9mjknj6vzf79xvgjwjln9m0000gn/T/RtmpTuaxI0/R.INSTALL65963b03396/SNPfiltR/R/filter_allele_balance.R:66:4: unexpected 'else'
65:     }
66:   }else
       ^
ERROR: unable to collate and parse R files for package ‘SNPfiltR’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/SNPfiltR’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/SNPfiltR’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/w3/n_9mjknj6vzf79xvgjwjln9m0000gn/T//RtmpXOseFi/file61b6ae00f0b/SNPfiltR_1.0.0.tar.gz’ had non-zero exit status

**Comment by DevonDeRaad** [comment]
Sorry about that, in my haste, an extra curly bracket caused an internal error in function filter_allele_balance(). Should be fixed now following commit 7d1a622.

**Comment by loukiaspi** [comment]
Yep, worked like a charm. It does indeed take time, as per your warning, but it worked in multiple datasets. Thank you
